name: Update

on:
  schedule:
    - cron: "0 */1 * * *" # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Octokit
        run: 
          npm install @octokit/rest
          npm install

      - name: Update stats.json
        env:
          GITHUB_TOKEN: ${{ secrets.FGPA_TOKEN }}
        run: |
          node index.mjs

      - name: Commit stats.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.json README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else 
            git commit -m "Update tamagitchi"
            git stash
            git pull origin main --rebase
            git stash pop
            git push origin HEAD:main
          fi

      # - name: Checkout profile repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: idksarah/idksarah  # change to your user
      #     token: ${{ secrets.FGPA_TOKEN }}
      #     path: profile-repo
      #     fetch-depth: 0

      # - name: Run update script (repo 2)
      #   working-directory: ./profile-repo
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.FGPA_TOKEN }}
      #   run: |


      # - name: Commit and push changes (repo 2)
      #   working-directory: ./profile-repo
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add stats.json
      #     if git diff --cached --quiet; then
      #       echo "No changes to commit"
      #     else
      #       git commit -m "Update stats"
      #       git stash
      #       git pull origin main --rebase
      #       git stash pop
      #       git push origin HEAD:main
      #     fi